### ISSUE TITLE
Call to Action: Help us test the compiled wheels to ensure they are stable!

### ISSUE THREAD

**Issue by ichard26** [ichard26/black-mypyc-wheels#12]
Hello!

So I'm Richard and I'm part of the core team that maintain the psf/black project. Black is an uncompromising Python autoformatter and it's become one of the most popular formatters out there. You might be wondering why I'm focusing my attention on improving the performance of Black, well it's because there's not that uncommon to run Black on save. The faster Black can start and finish formatting the file the smoother the experience gets :)

**Anyway I need your help to test out the experimental compiled wheels to ensure they don't experience any crashes or other quirks that don't happen with the normal interpreted wheel.** While it'd be nice to be able test compiled Black across many OSes, architectures, and Python runtimes, we simply don't have the CI resources to be able do that. In particular the M1 ARM wheels (and the ARM portion of the universal2 wheels) are straight up untested which is not ... great.

So what follows are the instructions to help us test the wheels:

> FYI: all 32-bit platforms and PyPy are not supported. For Windows ARM is not supported, and for Linux MUSL or ARM is not supported either at the moment. 

1. Download one of compiled wheels from this index: https://ichard26.github.io/black-mypyc-index/ - There's information on the main page but the TL;DR is that you need to pass `--extra-index-url https://ichard26.github.io/black-mypyc-index/simple/` to your pip install invocation.
2. Once downloaded and installed, please verify you actually got a compiled version by running `black --version` and checking for the `(compiled: yes)` bit in the output.
3. Note down the version, you'll need it for later
4. Use it as you would normally, y'all use Black in different ways and the more of that we can capture in the testing the better!
5. File an user field report issue here: https://github.com/ichard26/black-mypyc-wheels/issues/new/choose  

Thank you for helping us and I in particular out! Please lemme know if you have questions!

---

#### "I get `compiled: no` for step 2"

First of all please make sure your pip is up to date. The packaging setup is rather modern and only newer pips will understand the produced wheels. If that doesn't fix it then please try `python -m pip install black --force-reinstall --no-deps --index-url https://ichard26.github.io/black-mypyc-index/simple`. This command forces pip to only look at compiled wheel index so if this fails (after making sure you updated your pip!) then unfortunately I don't have support for your system.[^1] Note that if this succeeds, you'll have to install Black's deps manually as my personal index does not host the runtime deps for Black.[^2]

[^1]: Feel free to ask for support but please know it might not be feasible and/or will take some time
[^2]: I can look into hosting the dependencies too to avoid PyPI lookups and pip picking the wrong file but that will take time

**Comment by felix-hilden** [comment]
A small test report:

- Python 3.9.4 / virtualenv / Windows 10
- Wheel: `black-21.12b0-cp39-cp39-win_amd64.whl`

Runs:

- `black`: nothing to do
- `black -c "x=2"`: `x = 2`
- `black black/src`: 26 unchanged
- Formatting a bunch of my own smaller projects succeeded with and without changes

I'll keep using the wheel and report back here if any problems arise!

**Comment by ichard26** [comment]
Not relevant anymore since 22.1.0 has mypyc compiled wheels :tada:
