### ISSUE TITLE
[Field report]: It works wonderfully

### ISSUE THREAD

**Issue by whispersofthedawn** [ichard26/black-mypyc-wheels#13]
### Tested revision

21.11b2.dev14+gb336b39

### Environment - Python version

3.9.9

### Environment - OS & Architecture

Windows 11 (64-bit operating system, x64-based processor)

### Overall notes

- [X] Did you observe a performance improvement w/ the compiled wheels?
- [ ] Did you experience a crash or other flaky behaviour w/ the compiled wheels?

### Additional commentary & notes

Almost 2x speed improvements for me, great job!

**Comment by dawnofmidnight** [comment]
It's been a long while, now closing.

**Comment by whispersofthedawn** [comment]
It's been a long while, now closing.
