### ISSUE TITLE
black is the best

### ISSUE THREAD

**Issue by denballakh** [ichard26/black-mypyc-wheels#16]
### Tested revision

21.11b2.dev14+gb336b39

### Environment - Python version

CPython 3.10.0

### Environment - OS & Architecture

Windows 10 x64

### Overall notes

- [X] Did you observe a performance improvement w/ the compiled wheels?
- [ ] Did you experience a crash or other flaky behaviour w/ the compiled wheels?

### Additional commentary & notes

Ffter one month of using the compiled wheels:
No crashes, no new bugs. It's faster than before.

**Comment by ichard26** [comment]
Thank you!
