### ISSUE TITLE
Gaining control over the Black package on TestPyPI

### ISSUE THREAD

**Issue by ichard26** [ichard26/black-mypyc-wheels#18]
Hi @benoit-pierre, I believe you are the current owner of [the Black package on TestPyPI](https://test.pypi.org/project/black/). I'm one of Black's maintainers ([I'm listed on Black's authors list](https://github.com/psf/black/blob/main/AUTHORS.md) and [Black's maintainers list on PyPI](https://pypi.org/project/black/) if you want proof) and I would like to use TestPyPI to test out some release automation changes I'm currently working on. I'd appreciate if you could add me ([ichard26 on TestPyPI](https://test.pypi.org/user/ichard26/)) as an owner. (and I'll remove you if you're okay with that)

Thank you in advance!

**Comment by benoit-pierre** [comment]
Done.

**Comment by ichard26** [comment]
Thank you!
